name: Plugin release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{secrets.USER}}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.PASSWORD}}
      SIGNING_KEY: ${{secrets.KEY}}
      SIGNING_KEY_ID: ${{secrets.KEY_ID}}
      SIGNING_PASSWORD: ${{secrets.KEY_PASS}}

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to Maven Central
        run: ./gradlew publish